apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kommonitor

bases:
  - ./components/

resources:
- ingress.yaml
- issuer.yaml
- namespace.yaml

images:
- name: kommonitor/data-management
  newName: kommonitor/data-management
  newTag: 3.0.0
- name: kommonitor/importer
  newName: kommonitor/importer
  newTag: 3.2.2
- name: kommonitor/client-config
  newName: kommonitor/client-config
  newTag: 2.0.3
- name: kommonitor/processing-engine
  newName: kommonitor/processing-engine
  newTag: 2.0.2
- name: kommonitor/processing-scheduler
  newName: kommonitor/processing-scheduler
  newTag: 2.0.2
- name: kommonitor/web-client
  newName: kommonitor/web-client
  newTag: 2.2.0