apiVersion: apps/v1
kind: Deployment
metadata:
  name: kommonitor-importer
  labels:
    app: kommonitor-importer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kommonitor-importer
  template:
    metadata:
      labels:
        app: kommonitor-importer
    spec:
      containers:
      - name: kommonitor-importer
        image: kommonitor/importer:3.2.4
        imagePullPolicy: Always
        resources:
          requests:
            memory: "192M"
            cpu: "10m"
          limits:
            memory: "1024M"
            cpu: "1000m"
        ports:
        - containerPort: 8087
        envFrom:
        - configMapRef:
            name: kommonitor-importer
        - configMapRef:
            name: kommonitor-keycloak